name: r_store
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

#--------------- Packages ---------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  intl: 0.18.1
  logger: ^2.0.1
  url_launcher: ^6.1.12

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  # Product Specific



  #--------------- ./ Packages End ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  #----------------- Local Assets ---------------#
  assets:
    - assets/icons/brands/
    - assets/images/
    - assets/logos/

  #--------------- Local Fonts ---------------#
#  fonts:
#    family: poppins
#    fonts:
#      - asset: assets/fonts/Poppins-Black.ttf
#      - asset: assets/fonts/Poppins-BlackItalic.ttf
#      - asset: assets/fonts/Poppins-Bold.ttf
#      - asset: assets/fonts/Poppins-BoldItalic.ttf
#      - asset: assets/fonts/Poppins-ExtraBold.ttf
#      - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
#      - asset: assets/fonts/Poppins-Italic.ttf
#      - asset: assets/fonts/Poppins-Light.ttf
#      - asset: assets/fonts/Poppins-LightItalic.ttf
#      - asset: assets/fonts/Poppins-Medium.ttf
#      - asset: assets/fonts/Poppins-MediumItalic.ttf
#      - asset: assets/fonts/Poppins-Regular.ttf
#      - asset: assets/fonts/Poppins-SemiBold.ttf
#      - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
#      - asset: assets/fonts/Poppins-Thin.ttf
#      - asset: assets/fonts/Poppins-ThinItalic.ttf




